
gui:
  splitDiff: 'always'
  mainPanelSplitMode: 'vertical'
  border: 'double'
  theme:
    selectedLineBgColor:
      - underline
    inactiveBorderColor:
      - '#ababab'
    activeBorderColor:
      - yellow
      - bold

keybinding:
  universal:
    quit: null # disabled this bcus I don't like q for quit
    stashAllChanges: null # disable keymaps of s to prevent conflict with select
    select: 's'

# determines whether hitting 'esc' will quit the application when there is nothing to cancel/close
quitOnTopLevelReturn: true

git:
  paging:
    pager: delta --dark --side-by-side

# when opening or editing a file, this will open the same neovim instance
os:
  editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
  editCommand: 'nvim'
